import { useCallback, useEffect, useRef, useState } from 'react'
import {
  fetchProjectSession,
  getPromptByShare,
  getShareEvents,
  getShareState,
  type ProjectSessionResponse,
  type ShareEventsResponse,
  type ShareState,
} from '../api'
import { mocksEnabled } from '../lib/mocks'

export type PromptTarget = 'claude-code' | 'codex' | 'generic'

export interface AgentSession {
  slug: string
  token: string
  docUrl: string
}

export interface UseAgentSessionResult {
  session: AgentSession | null
  projectName: string | null
  shareState: ShareState | null
  events: ShareEventsResponse['events']
  error: string | null
  loading: boolean
  copyPrompt: (target: PromptTarget) => Promise<string>
}

const POLL_INTERVAL_MS = 4000
const EVENT_LIMIT = 100
const POLL_FAIL_THRESHOLD = 3

export function useAgentSession(apiBase: string, projectId: string | null): UseAgentSessionResult {
  const [session, setSession] = useState<AgentSession | null>(null)
  const [projectName, setProjectName] = useState<string | null>(null)
  const [shareState, setShareState] = useState<ShareState | null>(null)
  const [events, setEvents] = useState<ShareEventsResponse['events']>([])
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const cursorRef = useRef<number>(0)
  const activeProjectRef = useRef<string | null>(null)

  useEffect(() => {
    activeProjectRef.current = projectId
    setSession(null)
    setProjectName(null)
    setShareState(null)
    setEvents([])
    setError(null)
    cursorRef.current = 0

    if (!projectId) return

    if (mocksEnabled) {
      setSession({ slug: `mock-${projectId}`, token: 'mock-token', docUrl: `https://docs.example/${projectId}` })
      setProjectName(projectId)
      setLoading(false)
      return
    }

    setLoading(true)

    let cancelled = false
    fetchProjectSession(apiBase, projectId)
      .then((res: ProjectSessionResponse) => {
        if (cancelled || activeProjectRef.current !== projectId) return
        setSession({ slug: res.doc.slug, token: res.doc.token, docUrl: res.doc.docUrl })
        setProjectName(res.projectName)
      })
      .catch((err) => {
        if (cancelled || activeProjectRef.current !== projectId) return
        setError(err instanceof Error ? err.message : 'Could not start session')
      })
      .finally(() => {
        if (!cancelled && activeProjectRef.current === projectId) setLoading(false)
      })

    return () => {
      cancelled = true
    }
  }, [apiBase, projectId])

  useEffect(() => {
    if (!session) return
    if (mocksEnabled) return
    let cancelled = false
    let consecutiveFails = 0

    const tick = async () => {
      const [stateRes, eventsRes] = await Promise.allSettled([
        getShareState(apiBase, session.slug, session.token),
        getShareEvents(apiBase, session.slug, session.token, cursorRef.current),
      ])
      if (cancelled) return

      if (stateRes.status === 'fulfilled') setShareState(stateRes.value)
      if (eventsRes.status === 'fulfilled') {
        const res = eventsRes.value
        if (res.events.length > 0) {
          setEvents((prev) => {
            const seen = new Set(prev.map((e) => e.id))
            const merged = [...prev, ...res.events.filter((e) => !seen.has(e.id))]
            return merged.slice(-EVENT_LIMIT)
          })
          cursorRef.current = res.nextCursor
        }
      }

      const failures = [stateRes, eventsRes].filter((r) => r.status === 'rejected') as PromiseRejectedResult[]
      if (failures.length > 0) {
        consecutiveFails++
        for (const f of failures) console.warn('Agent session poll failed', f.reason)
        if (consecutiveFails >= POLL_FAIL_THRESHOLD) {
          setError('Lost connection to agent session — retrying')
        }
      } else if (consecutiveFails > 0) {
        consecutiveFails = 0
        setError(null)
      }
    }

    tick()
    const interval = window.setInterval(tick, POLL_INTERVAL_MS)
    return () => {
      cancelled = true
      window.clearInterval(interval)
    }
  }, [apiBase, session])

  const copyPrompt = useCallback(async (target: PromptTarget) => {
    if (!session) throw new Error('No session yet')
    if (mocksEnabled) {
      const prompt = `# Mock prompt for ${target}\nReview these Ready-for-Agent items at ${session.docUrl}\n(real prompt is generated by /api/v1/shares/.../prompt)`
      await navigator.clipboard.writeText(prompt)
      return prompt
    }
    const res = await getPromptByShare(apiBase, session.slug, session.token, target)
    await navigator.clipboard.writeText(res.prompt)
    return res.prompt
  }, [apiBase, session])

  return { session, projectName, shareState, events, error, loading, copyPrompt }
}
