import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

vi.mock('../api', () => ({ deleteExtensionComment: vi.fn(), listExtensionComments: vi.fn(), updateExtensionComment: vi.fn(), getProjectGitHubStatus: vi.fn() }))
import { deleteExtensionComment, getProjectGitHubStatus, listExtensionComments, updateExtensionComment, type ExtensionCommentRecord } from '../api'
import { ExtensionCommentsPage } from './ExtensionCommentsPage'

const first: ExtensionCommentRecord = { id: 'c1', pageUrl: 'https://example.com/path?q=1', pageHostname: 'example.com', x: 12.34, y: 56.78, selector: '#target', body: 'First comment', screenshotUrl: 'https://signed/image', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-01-01T00:00:00Z' }
const second: ExtensionCommentRecord = { ...first, id: 'c2', pageHostname: 'two.example', body: 'Second comment', screenshotUrl: null }

beforeEach(() => {
  vi.clearAllMocks()
  vi.mocked(listExtensionComments).mockResolvedValue({ items: [first, second], page: 1, limit: 20, total: 21 })
  vi.mocked(updateExtensionComment).mockImplementation(async (_api, _token, id, body) => ({ ...(id === 'c1' ? first : second), body }))
  vi.mocked(deleteExtensionComment).mockResolvedValue()
})
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.useRealTimers() })

describe('ExtensionCommentsPage', () => {
  it('refills the current page after deletion crosses a pagination boundary', async () => {
    const items = Array.from({ length: 20 }, (_, index) => ({ ...first, id: `item-${index}`, body: `Item ${index}` }))
    vi.mocked(listExtensionComments).mockResolvedValueOnce({ items, total: 21, page: 1, limit: 20 })
      .mockResolvedValueOnce({ items: [...items.slice(1), second], total: 20, page: 1, limit: 20 })
    render(<ExtensionCommentsPage apiBase="/api" accessToken="token" />)
    fireEvent.click(await screen.findByRole('button', { name: /Item 0/ }))
    fireEvent.click(screen.getByRole('button', { name: 'Delete' }))
    await screen.findByText('Second comment')
    expect(screen.queryByText('Item 0')).toBeNull()
    expect(screen.queryByRole('button', { name: 'Next' })).toBeNull()
    expect(listExtensionComments).toHaveBeenCalledTimes(2)
  })

  it('renews signed images on a timer and focus without discarding edits, tolerating failures and stale results', async () => {
    vi.useFakeTimers()
    const view = render(<ExtensionCommentsPage apiBase="/api" accessToken="token" />)
    await act(async () => {})
    fireEvent.click(screen.getByRole('button', { name: /First comment/ }))
    fireEvent.click(screen.getByRole('button', { name: 'Edit' }))
    fireEvent.change(screen.getByLabelText('Edit comment'), { target: { value: 'Unsaved' } })
    vi.mocked(listExtensionComments).mockResolvedValueOnce({ items: [{ ...first, screenshotUrl: 'https://signed/fresh' }], page: 1, total: 21, limit: 20 })
    await act(async () => { vi.advanceTimersByTime(240_000) })
    expect(screen.getByLabelText('Edit comment')).toHaveValue('Unsaved')
    expect(screen.getByAltText(`Screenshot of ${first.pageUrl}`)).toHaveAttribute('src', 'https://signed/fresh')
    vi.mocked(listExtensionComments).mockRejectedValueOnce(new Error('offline'))
    await act(async () => { fireEvent.focus(window) })
    expect(screen.getByLabelText('Edit comment')).toHaveValue('Unsaved')
    let resolve!: (value: any) => void
    vi.mocked(listExtensionComments).mockReturnValueOnce(new Promise((done) => { resolve = done }))
    await act(async () => { fireEvent.focus(window); fireEvent.focus(window) })
    await act(async () => { resolve({ items: [], total: 0 }) })
    vi.mocked(listExtensionComments).mockReturnValueOnce(new Promise((done) => { resolve = done }))
    fireEvent.focus(window); view.unmount()
    await act(async () => { resolve({ items: [], total: 0 }) })
  })
  it('shows personal details, pages, edits, and deletes', async () => {
    render(<ExtensionCommentsPage apiBase="/api" accessToken="token" />)
    expect(screen.getByText('Loading comments…')).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Coming soon' })).toBeNull()
    await screen.findByText('First comment')
    expect(screen.getByText('Select an extension comment')).toBeInTheDocument()
    expect(screen.getByText('Pick one of your extension comments from the list to see its page context and screenshot.')).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'Coming soon' })).toBeNull()
    fireEvent.click(screen.getByRole('button', { name: /First comment/ }))
    expect(screen.getByAltText(`Screenshot of ${first.pageUrl}`)).toHaveAttribute('src', 'https://signed/image')
    expect(screen.getByText('Pin 12.34%, 56.78%')).toBeInTheDocument()
    const open = vi.spyOn(window, 'open').mockImplementation(() => null)
    fireEvent.click(screen.getByRole('button', { name: 'Open page' })); expect(open).toHaveBeenCalledWith(first.pageUrl, '_blank', 'noopener,noreferrer')
    for (const name of ['Select', 'Ready for Agent', 'Mark Done', 'Reject', 'Accept to create issue']) expect(screen.queryByRole('button', { name })).toBeNull()

    fireEvent.click(screen.getByRole('button', { name: 'Next' }))
    await waitFor(() => expect(listExtensionComments).toHaveBeenCalledWith('/api', 'token', 2))
    fireEvent.click(screen.getByRole('button', { name: 'Previous' }))
    await waitFor(() => expect(listExtensionComments).toHaveBeenCalledWith('/api', 'token', 1))

    fireEvent.click(await screen.findByRole('button', { name: /First comment/ }))
    fireEvent.click(screen.getByRole('button', { name: 'Edit' }))
    fireEvent.change(screen.getByLabelText('Edit comment'), { target: { value: ' Updated ' } })
    fireEvent.click(screen.getByRole('button', { name: 'Save' }))
    await waitFor(() => expect(updateExtensionComment).toHaveBeenCalledWith('/api', 'token', 'c1', 'Updated'))
    await waitFor(() => expect(screen.getAllByText('Updated')).toHaveLength(2))

    fireEvent.click(screen.getAllByRole('button', { name: 'Edit' })[0]!); fireEvent.click(screen.getByRole('button', { name: 'Cancel' }))
    fireEvent.click(screen.getAllByRole('button', { name: 'Delete' })[0]!)
    await waitFor(() => expect(deleteExtensionComment).toHaveBeenCalledWith('/api', 'token', 'c1'))
    expect(screen.queryByText('Updated')).not.toBeInTheDocument()

  })

  it('shows empty and load error states', async () => {
    vi.mocked(listExtensionComments).mockResolvedValueOnce({ items: [], page: 1, limit: 20, total: 0 })
    const view = render(<ExtensionCommentsPage apiBase="/api" accessToken="token" />)
    await screen.findByText('No comments')
    expect(screen.getByText('No extension comments yet.')).toBeInTheDocument()
    expect(screen.getByRole('heading', { name: 'Try the CRRT extension' })).toBeInTheDocument()
    expect(screen.getByText('Comments you leave with the CRRT browser extension will appear here.')).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Coming soon' })).toBeDisabled()
    expect(screen.queryByText('Select an extension comment')).toBeNull()
    expect(screen.queryByRole('button', { name: 'Next' })).not.toBeInTheDocument(); view.unmount()
    vi.mocked(listExtensionComments).mockRejectedValueOnce('bad')
    render(<ExtensionCommentsPage apiBase="/api" accessToken="token" />)
    await screen.findByText('Could not load extension comments')
    expect(screen.queryByRole('button', { name: 'Coming soon' })).toBeNull()
  })

  it('keeps editing available when update or delete fails', async () => {
    vi.mocked(updateExtensionComment).mockRejectedValueOnce(new Error('update down')).mockRejectedValueOnce('bad')
    vi.mocked(deleteExtensionComment).mockRejectedValueOnce(new Error('delete down')).mockRejectedValueOnce('bad')
    render(<ExtensionCommentsPage apiBase="/api" accessToken="token" />); await screen.findByText('First comment')
    fireEvent.click(screen.getByRole('button', { name: /First comment/ }))
    fireEvent.click(screen.getAllByRole('button', { name: 'Edit' })[0]!); fireEvent.click(screen.getByRole('button', { name: 'Save' })); await screen.findByText('update down')
    fireEvent.click(screen.getByRole('button', { name: 'Save' })); await screen.findByText('Could not update comment')
    fireEvent.click(screen.getAllByRole('button', { name: 'Delete' })[0]!); await screen.findByText('delete down')
    fireEvent.click(screen.getAllByRole('button', { name: 'Delete' })[0]!); await screen.findByText('Could not delete comment')
  })

  it('navigates owned comments without status shortcuts or project requests', async () => {
    render(<ExtensionCommentsPage apiBase="/api" accessToken="token" />)
    await screen.findByText('First comment')
    fireEvent.keyDown(window, { key: 'k' })
    expect(screen.queryByRole('button', { name: 'Edit' })).toBeNull()
    fireEvent.keyDown(window, { key: 'j' })
    expect(screen.getByText('1/2')).toBeInTheDocument()
    fireEvent.keyDown(window, { key: 'ArrowDown' })
    expect(screen.getByText('2/2')).toBeInTheDocument()
    fireEvent.keyDown(window, { key: ' ' })
    expect(screen.getByText('2/2')).toBeInTheDocument()
    fireEvent.keyDown(window, { key: 'ArrowUp' })
    fireEvent.click(screen.getByRole('button', { name: 'Next comment' }))
    fireEvent.click(screen.getByRole('button', { name: 'Previous comment' }))
    fireEvent.keyDown(window, { key: 'j' }); fireEvent.keyDown(window, { key: 'k' })
    for (const modifier of ['metaKey', 'ctrlKey', 'altKey']) fireEvent.keyDown(window, { key: 'j', [modifier]: true })
    for (const key of ['a', 'm', 'd', 's', 'Escape']) fireEvent.keyDown(window, { key })
    expect(screen.getByText('1/2')).toBeInTheDocument()
    expect(getProjectGitHubStatus).not.toHaveBeenCalled()
    expect(updateExtensionComment).not.toHaveBeenCalled()
    expect(deleteExtensionComment).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole('button', { name: 'Edit' }))
    fireEvent.keyDown(screen.getByLabelText('Edit comment'), { key: 'j' })
    expect(screen.getByText('1/2')).toBeInTheDocument()
    fireEvent.change(screen.getByLabelText('Edit comment'), { target: { value: '   ' } })
    expect(screen.getByRole('button', { name: 'Save' })).toBeDisabled()
  })

  it('keeps selection stable during a save and preserves errors and the draft', async () => {
    let resolve!: (item: ExtensionCommentRecord) => void
    vi.mocked(updateExtensionComment).mockReturnValueOnce(new Promise((done) => { resolve = done }))
    render(<ExtensionCommentsPage apiBase="/api" accessToken="token" />)
    fireEvent.click(await screen.findByRole('button', { name: /First comment/ }))
    fireEvent.click(screen.getByRole('button', { name: 'Edit' }))
    fireEvent.change(screen.getByLabelText('Edit comment'), { target: { value: 'New body' } })
    fireEvent.click(screen.getByRole('button', { name: 'Save' }))
    expect(screen.getByLabelText('Edit comment')).toBeDisabled()
    expect(screen.getByRole('button', { name: 'Next' })).toBeDisabled()
    fireEvent.click(screen.getByRole('button', { name: /Second comment/ }))
    fireEvent.keyDown(window, { key: 'j' })
    expect(screen.getByText('1/2')).toBeInTheDocument()
    await act(async () => resolve({ ...first, body: 'New body' }))
    expect(screen.getAllByText('New body')).toHaveLength(2)
    fireEvent.click(screen.getByRole('button', { name: /Second comment/ }))
    expect(screen.getByText('2/2')).toBeInTheDocument()
  })

  it('returns to the previous page after deleting the last item on the last page', async () => {
    vi.mocked(listExtensionComments).mockResolvedValueOnce({ items: [first], total: 21, page: 1, limit: 20 })
      .mockResolvedValueOnce({ items: [second], total: 21, page: 2, limit: 20 })
      .mockResolvedValueOnce({ items: [first], total: 20, page: 1, limit: 20 })
    render(<ExtensionCommentsPage apiBase="/api" accessToken="token" />)
    await screen.findByText('First comment')
    fireEvent.click(screen.getByRole('button', { name: 'Next' }))
    fireEvent.click(await screen.findByRole('button', { name: /Second comment/ }))
    fireEvent.click(screen.getByRole('button', { name: 'Delete' }))
    await screen.findByText('First comment')
    expect(listExtensionComments).toHaveBeenLastCalledWith('/api', 'token', 1)
    expect(screen.queryByText('Page 2 of 2')).toBeNull()
    expect(screen.queryByRole('button', { name: 'Edit' })).toBeNull()
  })

  it('ignores late successful and failed page loads after unmount', async () => {
    let resolve!: (result: Awaited<ReturnType<typeof listExtensionComments>>) => void
    let reject!: (error: Error) => void
    vi.mocked(listExtensionComments).mockReturnValueOnce(new Promise((done) => { resolve = done }))
      .mockReturnValueOnce(new Promise((_, fail) => { reject = fail }))
    const view = render(<ExtensionCommentsPage apiBase="/api" accessToken="old" />)
    view.rerender(<ExtensionCommentsPage apiBase="/api" accessToken="new" />)
    await act(async () => resolve({ items: [first], total: 1, page: 1, limit: 20 }))
    expect(screen.queryByText('First comment')).toBeNull()
    expect(screen.getByText('Loading comments…')).toBeInTheDocument()
    view.unmount()
    await act(async () => reject(new Error('late failure')))
  })
})
