import { act, fireEvent, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, expect, it, vi } from 'vitest'
import { ProjectDomainAccess } from './ProjectDomainAccess'
import { domainAccessApi } from '../domain-access-api'
vi.mock('../domain-access-api', () => ({ domainAccessApi: vi.fn() }))
const api = { domains: vi.fn(), requests: vi.fn(), addDomain: vi.fn(), removeDomain: vi.fn(), review: vi.fn() }
const changed = vi.fn()
const request = { id: 'r', attempt: 1, email: 'person@company.com' }
const props = { apiBase: '/api', accessToken: 'token', projectKey: 'p', onMembersChanged: changed }
beforeEach(() => {
  vi.resetAllMocks()
  vi.mocked(domainAccessApi).mockReturnValue(api as never)
  api.domains.mockResolvedValue([]); api.requests.mockResolvedValue([])
  api.addDomain.mockResolvedValue({}); api.removeDomain.mockResolvedValue({}); api.review.mockResolvedValue({})
})
it('loads empty states and adds/removes domains using keyboard-accessible controls', async () => {
  const user = userEvent.setup()
  render(<ProjectDomainAccess {...props} />)
  expect(screen.getByRole('status')).toHaveTextContent('Loading')
  expect(await screen.findByText('No company domains configured.')).toBeInTheDocument()
  expect(screen.getByText('No pending access requests.')).toBeInTheDocument()
  expect(screen.getByRole('button', { name: 'Add domain' })).toBeDisabled()
  await user.type(screen.getByLabelText('Company email domain'), '@Company.com')
  api.domains.mockResolvedValue([{ domain: 'company.com' }])
  await user.keyboard('{Enter}')
  await waitFor(() => expect(api.addDomain).toHaveBeenCalledWith('p', '@Company.com'))
  await waitFor(() => expect(screen.getByLabelText('Company email domain')).toHaveValue(''))
  api.domains.mockResolvedValue([])
  await user.click(screen.getByRole('button', { name: 'Remove company.com' }))
  await waitFor(() => expect(api.removeDomain).toHaveBeenCalledWith('p', 'company.com'))
  expect(await screen.findByText('No company domains configured.')).toBeInTheDocument()
})
it('defaults to member, allows selecting guest/admin and reviews the displayed attempt', async () => {
  api.requests.mockResolvedValue([{ ...request, attempt: 2 }])
  render(<ProjectDomainAccess {...props} />)
  const role = await screen.findByLabelText('Access role for person@company.com')
  expect(role).toHaveValue('member')
  expect(Array.from((role as HTMLSelectElement).options).map(o => o.value)).toEqual(['member', 'guest', 'admin'])
  fireEvent.change(role, { target: { value: 'guest' } })
  fireEvent.click(screen.getByRole('button', { name: 'Accept person@company.com' }))
  await waitFor(() => expect(api.review).toHaveBeenCalledWith('p', 'r', 'approved', 'guest', 2))
  await waitFor(() => expect(changed).toHaveBeenCalledTimes(1))
  fireEvent.click(screen.getByRole('button', { name: 'Deny person@company.com' }))
  await waitFor(() => expect(api.review).toHaveBeenCalledWith('p', 'r', 'declined', 'guest', 2))
  await waitFor(() => expect(changed).toHaveBeenCalledTimes(2))
})
it('retains invalid domain input, shows stale review errors and allows refresh', async () => {
  api.domains.mockRejectedValueOnce(new Error('Permission lost'))
  render(<ProjectDomainAccess {...props} />)
  expect(await screen.findByRole('alert')).toHaveTextContent('Permission lost')
  api.requests.mockResolvedValue([request])
  fireEvent.click(screen.getByRole('button', { name: 'Refresh access' }))
  await screen.findByText(request.email)
  fireEvent.change(screen.getByLabelText('Company email domain'), { target: { value: '*' } })
  api.addDomain.mockRejectedValueOnce(new Error('Invalid domain'))
  fireEvent.click(screen.getByRole('button', { name: 'Add domain' }))
  await waitFor(() => expect(screen.getByRole('alert')).toHaveTextContent('Invalid domain'))
  expect(screen.getByLabelText('Company email domain')).toHaveValue('*')
  api.review.mockRejectedValueOnce(new Error('Already reviewed'))
  fireEvent.click(screen.getByRole('button', { name: 'Accept person@company.com' }))
  await waitFor(() => expect(screen.getByRole('alert')).toHaveTextContent('Already reviewed'))
  expect(changed).not.toHaveBeenCalled()
})
it('disables all mutations while an action is pending and isolates project switching', async () => {
  let resolve!: (value: object) => void
  api.requests.mockResolvedValue([request])
  api.review.mockReturnValue(new Promise(r => { resolve = r }))
  const view = render(<ProjectDomainAccess key="p" {...props} />)
  await screen.findByText(request.email)
  fireEvent.click(screen.getByRole('button', { name: 'Deny person@company.com' }))
  expect(screen.getByRole('button', { name: 'Accept person@company.com' })).toBeDisabled()
  expect(screen.getByLabelText('Access role for person@company.com')).toBeDisabled()
  api.requests.mockResolvedValue([])
  view.rerender(<ProjectDomainAccess key="next" {...props} projectKey="next" />)
  await screen.findByText('No pending access requests.')
  await act(async () => { resolve({}) })
  expect(changed).not.toHaveBeenCalled()
  expect(api.domains).toHaveBeenLastCalledWith('next')
})
