import { DocsLayout } from '../DocsLayout'
import {
  Callout,
  CodeBlock,
  H2,
  H3,
  InlineCode,
  NextStep,
  Ol,
  P,
  PropsTable,
  Section,
  Strong,
  Ul,
} from '../Prose'

interface InstallPageProps {
  pathname: string
  onNavigate: (path: string) => void
}

const installSnippet = `# pick your package manager
pnpm add @thedesignproject/crrt
npm install @thedesignproject/crrt
bun add @thedesignproject/crrt
yarn add @thedesignproject/crrt`

const mountSnippet = `import { FeedbackWidget } from '@thedesignproject/crrt'

export default function App() {
  return (
    <>
      <YourApp />
      <FeedbackWidget
        projectId="proj_your_app_name"
        apiBase="https://crrt.ai/api"
      />
    </>
  )
}`

const nextAppSnippet = `// app/providers.tsx
'use client'

import { FeedbackWidget } from '@thedesignproject/crrt'

export function Providers({ children }: { children: React.ReactNode }) {
  return (
    <>
      {children}
      <FeedbackWidget projectId="proj_your_app_name" />
    </>
  )
}`

export function InstallPage({ pathname, onNavigate }: InstallPageProps) {
  return (
    <DocsLayout
      pathname={pathname}
      onNavigate={onNavigate}
      marker="install"
      title="Install the widget."
      description="Add CRRT to any React app and start collecting visual feedback in about two minutes."
    >
      <Section>
        <H2>1. Add the package</H2>
        <P>
          CRRT ships as <InlineCode>@thedesignproject/crrt</InlineCode> on npm. Pick your package manager —
          they all work.
        </P>
        <CodeBlock language="bash" code={installSnippet} />
      </Section>

      <Section>
        <H2>2. Drop it in your app root</H2>
        <P>
          Mount the widget once, alongside your app tree. Reviewers can press{' '}
          <InlineCode>C</InlineCode> on any page to drop a CRRT on any element.
        </P>
        <CodeBlock language="tsx" code={mountSnippet} />

        <Callout tone="info">
          <Strong>projectId</Strong> scopes feedback to a specific app — get yours from the dashboard after
          creating a project. <Strong>apiBase</Strong> defaults to <InlineCode>https://crrt.ai/api</InlineCode>,
          so you can omit it unless you're self-hosting.
        </Callout>
      </Section>

      <Section>
        <H2>Props</H2>
        <PropsTable
          rows={[
            {
              name: 'projectId',
              type: 'string',
              required: true,
              description: <>The project public key, e.g. <InlineCode>proj_acme_marketing</InlineCode>. Generated by the dashboard.</>,
            },
            {
              name: 'apiBase',
              type: 'string',
              description: <>Backend URL. Defaults to <InlineCode>https://crrt.ai/api</InlineCode>. Override when self-hosting.</>,
            },
          ]}
        />
      </Section>

      <Section>
        <H2>Framework notes</H2>

        <H3>Next.js (App Router)</H3>
        <P>
          The widget renders client-side. Mount it inside a <InlineCode>'use client'</InlineCode> providers
          component so the rest of your tree can stay server-rendered.
        </P>
        <CodeBlock language="tsx" code={nextAppSnippet} />

        <H3>Next.js (Pages Router)</H3>
        <P>
          Mount inside <InlineCode>pages/_app.tsx</InlineCode> alongside the page render. No extra
          configuration needed.
        </P>

        <H3>Vite, CRA, Remix, anything else</H3>
        <P>
          Mount once in your root component. The widget is SSR-safe: it no-ops during server render and
          activates on hydration.
        </P>
      </Section>

      <Section>
        <H2>Requirements</H2>
        <Ul>
          <li>React 18 or 19 on the consuming app.</li>
          <li>A modern browser with <InlineCode>structuredClone</InlineCode> and the Clipboard API (Chrome 76+, Safari 14+, Firefox 94+).</li>
          <li>An <InlineCode>apiBase</InlineCode> that responds to the public endpoints — covered automatically if you use <InlineCode>crrt.ai</InlineCode>.</li>
        </Ul>
      </Section>

      <Section>
        <H2>Verify the install</H2>
        <Ol>
          <li>Open your app in a browser tab.</li>
          <li>Press <InlineCode>C</InlineCode> — a crosshair should activate.</li>
          <li>Click any element. A pin drops, a popover opens, write a note.</li>
          <li>Sign into <InlineCode>crrt.ai/dashboard</InlineCode> and confirm the comment lands on your project.</li>
        </Ol>
        <Callout tone="warn">
          Nothing happens when you press <InlineCode>C</InlineCode>? Check that the widget actually mounted
          (it returns <InlineCode>null</InlineCode> during SSR), and that <Strong>projectId</Strong> matches a
          project you've created in the dashboard.
        </Callout>
      </Section>

      <NextStep href="/docs/agent-handoff" label="hand off feedback to your AI agent" onNavigate={onNavigate} />
    </DocsLayout>
  )
}
